=== Dabolus/cr-card-maker/src/templates/$schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "type": "object",
  "definitions": {
    "Rarity": {
      "type": "string",
      "enum": ["common", "rare", "epic", "legendary", "champion"]
    },
    "Type": {
      "type": "string",
      "enum": ["troop", "building", "spell", "tower-troop", "ruler"]
    },
    "ColorValue": {
      "type": ["string", "array"],
      "items": {
        "type": "string"
      },
      "minItems": 1
    },
    "TextAlign": {
      "type": "string",
      "enum": ["left", "right", "center"]
    },
    "TextBaseline": {
      "type": "string",
      "enum": ["top", "middle", "bottom"]
    },
    "Color": {
      "oneOf": [
        {
          "$ref": "#/definitions/ColorValue"
        },
        {
          "type": "object",
          "properties": {
            "common": {
              "$ref": "#/definitions/ColorValue"
            },
            "rare": {
              "$ref": "#/definitions/ColorValue"
            },
            "epic": {
              "$ref": "#/definitions/ColorValue"
            },
            "legendary": {
              "$ref": "#/definitions/ColorValue"
            },
            "champion": {
              "$ref": "#/definitions/ColorValue"
            }
          },
          "required": ["common", "rare", "epic", "legendary", "champion"],
          "additionalProperties": false
        }
      ]
    },
    "Url": {
      "oneOf": [
        {
          "type": "string"
        },
        {
          "type": "object",
          "properties": {
            "common": {
              "type": "string"
            },
            "rare": {
              "type": "string"
            },
            "epic": {
              "type": "string"
            },
            "legendary": {
              "type": "string"
            },
            "champion": {
              "type": "string"
            }
          },
          "required": ["common", "rare", "epic", "legendary", "champion"],
          "additionalProperties": false
        }
      ]
    },
    "Fields": {
      "type": "object",
      "properties": {
        "card-name": {
          "type": "object",
          "properties": {
            "x": {
              "type": "integer"
            },
            "y": {
              "type": "integer"
            },
            "fontSize": {
              "type": "integer"
            },
            "maxWidth": {
              "type": "integer"
            },
            "textAlign": {
              "$ref": "#/definitions/TextAlign"
            },
            "color": {
              "$ref": "#/definitions/ColorValue"
            }
          },
          "required": ["x", "y", "fontSize", "maxWidth", "color"],
          "additionalProperties": false
        },
        "level": {
          "type": "object",
          "properties": {
            "x": {
              "type": "integer"
            },
            "y": {
              "type": "integer"
            },
            "fontSize": {
              "type": "integer"
            },
            "color": {
              "$ref": "#/definitions/Color"
            }
          },
          "required": ["x", "y", "fontSize", "color"],
          "additionalProperties": false
        },
        "image": {
          "type": "object",
          "properties": {
            "x": {
              "type": "integer"
            },
            "y": {
              "type": "integer"
            },
            "width": {
              "type": "integer"
            },
            "height": {
              "type": "integer"
            }
          },
          "required": ["x", "y", "width", "height"],
          "additionalProperties": false
        },
        "elixir-cost": {
          "type": "object",
          "properties": {
            "x": {
              "type": "integer"
            },
            "y": {
              "type": "integer"
            },
            "width": {
              "type": "integer"
            },
            "height": {
              "type": "integer"
            },
            "fontSize": {
              "type": "integer"
            }
          },
          "required": ["x", "y", "width", "height", "fontSize"],
          "additionalProperties": false
        },
        "rarity-background": {
          "type": "object",
          "properties": {
            "x": {
              "type": "integer"
            },
            "y": {
              "type": "integer"
            },
            "width": {
              "type": "integer"
            },
            "height": {
              "type": "integer"
            },
            "url": {
              "$ref": "#/definitions/Url"
            }
          },
          "required": ["x", "y", "width", "height", "url"],
          "additionalProperties": false
        },
        "rarity-label": {
          "type": "object",
          "properties": {
            "x": {
              "type": "integer"
            },
            "y": {
              "type": "integer"
            },
            "fontSize": {
              "type": "integer"
            },
            "maxWidth": {
              "type": "integer"
            },
            "textAlign": {
              "$ref": "#/definitions/TextAlign"
            },
            "color": {
              "$ref": "#/definitions/Color"
            }
          },
          "required": ["x", "y", "fontSize", "maxWidth", "color"],
          "additionalProperties": false
        },
        "rarity-value": {
          "type": "object",
          "properties": {
            "x": {
              "type": "integer"
            },
            "y": {
              "type": "integer"
            },
            "fontSize": {
              "type": "integer"
            },
            "maxWidth": {
              "type": "integer"
            },
            "textAlign": {
              "$ref": "#/definitions/TextAlign"
            },
            "color": {
              "$ref": "#/definitions/Color"
            }
          },
          "required": ["x", "y", "fontSize", "maxWidth", "color"],
          "additionalProperties": false
        },
        "type-background": {
          "type": "object",
          "properties": {
            "x": {
              "type": "integer"
            },
            "y": {
              "type": "integer"
            },
            "width": {
              "type": "integer"
            },
            "height": {
              "type": "integer"
            },
            "url": {
              "$ref": "#/definitions/Url"
            }
          },
          "required": ["x", "y", "width", "height", "url"],
          "additionalProperties": false
        },
        "type-label": {
          "type": "object",
          "properties": {
            "x": {
              "type": "integer"
            },
            "y": {
              "type": "integer"
            },
            "fontSize": {
              "type": "integer"
            },
            "maxWidth": {
              "type": "integer"
            },
            "textAlign": {
              "$ref": "#/definitions/TextAlign"
            },
            "color": {
              "$ref": "#/definitions/Color"
            }
          },
          "required": ["x", "y", "fontSize", "maxWidth", "color"],
          "additionalProperties": false
        },
        "type-value": {
          "type": "object",
          "properties": {
            "x": {
              "type": "integer"
            },
            "y": {
              "type": "integer"
            },
            "fontSize": {
              "type": "integer"
            },
            "maxWidth": {
              "type": "integer"
            },
            "textAlign": {
              "$ref": "#/definitions/TextAlign"
            },
            "color": {
              "$ref": "#/definitions/Color"
            }
          },
          "required": ["x", "y", "fontSize", "maxWidth", "color"],
          "additionalProperties": false
        },
        "description": {
          "type": "object",
          "properties": {
            "x": {
              "type": "integer"
            },
            "y": {
              "type": "integer"
            },
            "maxWidth": {
              "type": "integer"
            },
            "fontSize": {
              "type": "integer"
            },
            "lineHeight": {
              "type": "integer"
            },
            "maxLines": {
              "type": "integer",
              "minimum": 1,
              "maximum": 20
            },
            "textAlign": {
              "$ref": "#/definitions/TextAlign"
            },
            "textBaseline": {
              "$ref": "#/definitions/TextBaseline"
            },
            "color": {
              "$ref": "#/definitions/ColorValue"
            }
          },
          "required": [
            "x",
            "y",
            "maxWidth",
            "fontSize",
            "lineHeight",
            "maxLines",
            "color"
          ],
          "additionalProperties": false
        },
        "stats": {
          "type": "object",
          "properties": {
            "x": {
              "type": "integer"
            },
            "y": {
              "type": "integer"
            },
            "gapX": {
              "type": "integer"
            },
            "gapY": {
              "type": "integer"
            },
            "maxItems": {
              "type": "integer",
              "min": 1,
              "max": 20
            },
            "itemsPerRow": {
              "type": "integer",
              "min": 1,
              "max": 10
            },
            "items": {
              "type": "object",
              "properties": {
                "width": {
                  "type": "integer"
                },
                "height": {
                  "type": "integer"
                },
                "evenBackground": {
                  "type": "string"
                },
                "oddBackground": {
                  "type": "string"
                },
                "icon": {
                  "type": "object",
                  "properties": {
                    "dx": {
                      "type": "integer"
                    },
                    "dy": {
                      "type": "integer"
                    },
                    "width": {
                      "type": "integer"
                    },
                    "height": {
                      "type": "integer"
                    },
                    "backgroundColor": {
                      "$ref": "#/definitions/ColorValue"
                    }
                  },
                  "required": ["dx", "dy", "width", "height"],
                  "additionalProperties": false
                },
                "name": {
                  "type": "object",
                  "properties": {
                    "dx": {
                      "type": "integer"
                    },
                    "dy": {
                      "type": "integer"
                    },
                    "fontFamily": {
                      "type": "string"
                    },
                    "fontSize": {
                      "type": "integer"
                    },
                    "maxWidth": {
                      "type": "integer"
                    },
                    "color": {
                      "$ref": "#/definitions/ColorValue"
                    }
                  },
                  "required": ["dx", "dy", "fontSize", "maxWidth", "color"],
                  "additionalProperties": false
                },
                "value": {
                  "type": "object",
                  "properties": {
                    "dx": {
                      "type": "integer"
                    },
                    "dy": {
                      "type": "integer"
                    },
                    "fontSize": {
                      "type": "integer"
                    },
                    "maxWidth": {
                      "type": "integer"
                    },
                    "color": {
                      "$ref": "#/definitions/ColorValue"
                    }
                  },
                  "required": ["dx", "dy", "fontSize", "maxWidth", "color"],
                  "additionalProperties": false
                }
              },
              "required": ["width", "height", "icon", "name", "value"],
              "additionalProperties": false
            }
          },
          "required": [
            "x",
            "y",
            "gapX",
            "gapY",
            "maxItems",
            "itemsPerRow",
            "items"
          ],
          "additionalProperties": false
        }
      },
      "additionalProperties": false
    }
  },
  "properties": {
    "$schema": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "width": {
      "type": "integer"
    },
    "height": {
      "type": "integer"
    },
    "background": {
      "type": "string"
    },
    "supported-rarities": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/Rarity"
      },
      "minItems": 1,
      "uniqueItems": true
    },
    "supported-types": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/Type"
      },
      "minItems": 1,
      "uniqueItems": true
    },
    "fields": {
      "$ref": "#/definitions/Fields"
    },
    "pages": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": { "type": "string" },
          "x": { "type": "integer" },
          "y": { "type": "integer" },
          "width": { "type": "integer" },
          "height": { "type": "integer" },
          "background": { "type": "string" },
          "fields": {
            "$ref": "#/definitions/Fields"
          }
        },
        "required": [
          "name",
          "x",
          "y",
          "width",
          "height",
          "background",
          "fields"
        ]
      }
    },
    "i18n": {
      "type": "object",
      "patternProperties": {
        "^[a-z]{2}$": {
          "type": "object",
          "properties": {
            "name": {
              "type": "string"
            },
            "level": {
              "type": "string"
            },
            "rarity-label": {
              "type": "string"
            },
            "rarity-common": {
              "type": "string"
            },
            "rarity-rare": {
              "type": "string"
            },
            "rarity-epic": {
              "type": "string"
            },
            "rarity-legendary": {
              "type": "string"
            },
            "rarity-champion": {
              "type": "string"
            },
            "type-label": {
              "type": "string"
            },
            "type-troop": {
              "type": "string"
            },
            "type-building": {
              "type": "string"
            },
            "type-spell": {
              "type": "string"
            },
            "type-tower-troop": {
              "type": "string"
            }
          },
          "additionalProperties": false
        }
      },
      "additionalProperties": false
    }
  },
  "required": ["name", "width", "height"],
  "additionalProperties": false
}

=== Dabolus/cr-card-maker/src/templates/standard.json
{
  "$schema": "./$schema.json",
  "name": "Standard",
  "width": 989,
  "height": 1240,
  "supported-rarities": ["common", "rare", "epic", "legendary"],
  "supported-types": ["troop", "building", "spell"],
  "fields": {
    "card-name": {
      "x": 649,
      "y": 88,
      "fontSize": 58,
      "maxWidth": 660,
      "color": "#fff"
    },
    "level": {
      "x": 649,
      "y": 154,
      "fontSize": 40,
      "color": {
        "common": "#a4cbfa",
        "rare": "#f7ce76",
        "epic": "#f19ef9",
        "legendary": ["#9f6", "#fff", "#f9f", "#ff9", "#66fffc"],
        "champion": ["#f9dd50", "#fdfadf"]
      }
    },
    "image": {
      "x": 31,
      "y": 47,
      "width": 242,
      "height": 332
    },
    "elixir-cost": {
      "x": 15,
      "y": 49,
      "width": 63,
      "height": 75,
      "fontSize": 41
    },
    "rarity-background": {
      "x": 307,
      "y": 307,
      "width": 228,
      "height": 85,
      "url": {
        "common": "/cards-assets/rarity-backgrounds/standard/common.png",
        "rare": "/cards-assets/rarity-backgrounds/standard/rare.png",
        "epic": "/cards-assets/rarity-backgrounds/standard/epic.png",
        "legendary": "/cards-assets/rarity-backgrounds/standard/legendary.png",
        "champion": "/cards-assets/rarity-backgrounds/standard/legendary.png"
      }
    },
    "rarity-label": {
      "x": 428,
      "y": 331,
      "fontSize": 28,
      "maxWidth": 150,
      "textAlign": "center",
      "color": {
        "common": "#3a568d",
        "rare": "#7a3f15",
        "epic": "#5c1d76",
        "legendary": "#2e6851",
        "champion": "#815e1f"
      }
    },
    "rarity-value": {
      "x": 428,
      "y": 390,
      "fontSize": 34,
      "maxWidth": 190,
      "textAlign": "center",
      "color": {
        "common": "#a7c9fa",
        "rare": "#f2d171",
        "epic": "#ddb3f9",
        "legendary": ["#9f6", "#fff", "#f9f", "#ff9", "#66fffc"],
        "champion": ["#f9dd50", "#fdfadf"]
      }
    },
    "type-background": {
      "x": 565,
      "y": 307,
      "width": 228,
      "height": 85,
      "url": {
        "common": "/cards-assets/rarity-backgrounds/standard/common.png",
        "rare": "/cards-assets/rarity-backgrounds/standard/rare.png",
        "epic": "/cards-assets/rarity-backgrounds/standard/epic.png",
        "legendary": "/cards-assets/rarity-backgrounds/standard/legendary.png",
        "champion": "/cards-assets/rarity-backgrounds/standard/legendary.png"
      }
    },
    "type-label": {
      "x": 685,
      "y": 331,
      "fontSize": 28,
      "maxWidth": 190,
      "textAlign": "center",
      "color": {
        "common": "#3a568d",
        "rare": "#7a3f15",
        "epic": "#5c1d76",
        "legendary": "#2e6851",
        "champion": "#815e1f"
      }
    },
    "type-value": {
      "x": 685,
      "y": 390,
      "fontSize": 34,
      "maxWidth": 190,
      "textAlign": "center",
      "color": {
        "common": "#a7c9fa",
        "rare": "#f2d171",
        "epic": "#ddb3f9",
        "legendary": ["#9f6", "#fff", "#f9f", "#ff9", "#66fffc"],
        "champion": ["#f9dd50", "#fdfadf"]
      }
    }
  },
  "pages": [
    {
      "name": "Stats",
      "x": 0,
      "y": 0,
      "width": 989,
      "height": 1240,
      "background": "/cards-assets/backgrounds/standard-stats.png",
      "fields": {
        "stats": {
          "x": 58,
          "y": 486,
          "gapX": 19,
          "gapY": 6,
          "maxItems": 14,
          "itemsPerRow": 2,
          "items": {
            "width": 425,
            "height": 85,
            "oddBackground": "/cards-assets/backgrounds/standard-stat-bg.svg",
            "evenBackground": "/cards-assets/backgrounds/standard-stat-bg.svg",
            "icon": {
              "dx": 8,
              "dy": 4,
              "width": 73,
              "height": 73,
              "backgroundColor": "#1d232e"
            },
            "name": {
              "dx": 90,
              "dy": 12,
              "fontSize": 33,
              "maxWidth": 330,
              "color": "#384457"
            },
            "value": {
              "dx": 90,
              "dy": 51,
              "fontSize": 33,
              "maxWidth": 330,
              "color": "#fff"
            }
          }
        }
      }
    },
    {
      "name": "Description",
      "x": 0,
      "y": 0,
      "width": 989,
      "height": 1240,
      "background": "/cards-assets/backgrounds/standard-description.png",
      "fields": {
        "description": {
          "x": 495,
          "y": 532,
          "maxWidth": 760,
          "fontSize": 40,
          "lineHeight": 44,
          "maxLines": 9,
          "textBaseline": "middle",
          "color": "#4a566b"
        }
      }
    }
  ],
  "i18n": {
    "en": {
      "name": "{{cardName}}",
      "level": "Level {{level}}",
      "rarity-label": "RARITY",
      "rarity-common": "Common",
      "rarity-rare": "Rare",
      "rarity-epic": "Epic",
      "rarity-legendary": "Legendary",
      "rarity-champion": "Champion",
      "type-label": "TYPE",
      "type-troop": "Troop",
      "type-building": "Building",
      "type-spell": "Spell",
      "type-tower-troop": "Tower Troop"
    }
  }
}
